/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OverOnsRouteImport } from './routes/over-ons'
import { Route as GalerijRouteImport } from './routes/galerij'
import { Route as DrankenRouteImport } from './routes/dranken'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BorrelkaartRouteImport } from './routes/borrelkaart'
import { Route as BierkaartRouteImport } from './routes/bierkaart'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OverOnsRoute = OverOnsRouteImport.update({
  id: '/over-ons',
  path: '/over-ons',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerijRoute = GalerijRouteImport.update({
  id: '/galerij',
  path: '/galerij',
  getParentRoute: () => rootRouteImport,
} as any)
const DrankenRoute = DrankenRouteImport.update({
  id: '/dranken',
  path: '/dranken',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BorrelkaartRoute = BorrelkaartRouteImport.update({
  id: '/borrelkaart',
  path: '/borrelkaart',
  getParentRoute: () => rootRouteImport,
} as any)
const BierkaartRoute = BierkaartRouteImport.update({
  id: '/bierkaart',
  path: '/bierkaart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bierkaart': typeof BierkaartRoute
  '/borrelkaart': typeof BorrelkaartRoute
  '/contact': typeof ContactRoute
  '/dranken': typeof DrankenRoute
  '/galerij': typeof GalerijRoute
  '/over-ons': typeof OverOnsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bierkaart': typeof BierkaartRoute
  '/borrelkaart': typeof BorrelkaartRoute
  '/contact': typeof ContactRoute
  '/dranken': typeof DrankenRoute
  '/galerij': typeof GalerijRoute
  '/over-ons': typeof OverOnsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bierkaart': typeof BierkaartRoute
  '/borrelkaart': typeof BorrelkaartRoute
  '/contact': typeof ContactRoute
  '/dranken': typeof DrankenRoute
  '/galerij': typeof GalerijRoute
  '/over-ons': typeof OverOnsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bierkaart'
    | '/borrelkaart'
    | '/contact'
    | '/dranken'
    | '/galerij'
    | '/over-ons'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bierkaart'
    | '/borrelkaart'
    | '/contact'
    | '/dranken'
    | '/galerij'
    | '/over-ons'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/bierkaart'
    | '/borrelkaart'
    | '/contact'
    | '/dranken'
    | '/galerij'
    | '/over-ons'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BierkaartRoute: typeof BierkaartRoute
  BorrelkaartRoute: typeof BorrelkaartRoute
  ContactRoute: typeof ContactRoute
  DrankenRoute: typeof DrankenRoute
  GalerijRoute: typeof GalerijRoute
  OverOnsRoute: typeof OverOnsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over-ons': {
      id: '/over-ons'
      path: '/over-ons'
      fullPath: '/over-ons'
      preLoaderRoute: typeof OverOnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerij': {
      id: '/galerij'
      path: '/galerij'
      fullPath: '/galerij'
      preLoaderRoute: typeof GalerijRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dranken': {
      id: '/dranken'
      path: '/dranken'
      fullPath: '/dranken'
      preLoaderRoute: typeof DrankenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/borrelkaart': {
      id: '/borrelkaart'
      path: '/borrelkaart'
      fullPath: '/borrelkaart'
      preLoaderRoute: typeof BorrelkaartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bierkaart': {
      id: '/bierkaart'
      path: '/bierkaart'
      fullPath: '/bierkaart'
      preLoaderRoute: typeof BierkaartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BierkaartRoute: BierkaartRoute,
  BorrelkaartRoute: BorrelkaartRoute,
  ContactRoute: ContactRoute,
  DrankenRoute: DrankenRoute,
  GalerijRoute: GalerijRoute,
  OverOnsRoute: OverOnsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
